"""Band Gap engine.

Overall band = mean of available skill bands, rounded to the nearest 0.5.
The lowest skill is the highest-leverage place to improve; within Writing/Speaking
the lowest criterion is the named blocker. Explanations are pulled from real
mistake data — never generated by AI at read time.
"""
from collections import defaultdict
from statistics import mean

from sqlalchemy.orm import Session

from app.domain.models.mistake import Mistake
from app.application.analytics.links import practice_href
from app.application.analytics.sources import skill_bands, latest_feedback, recent_submission_ids
from app.domain.band import round_ielts as _round_half

DEFAULT_TARGET = 7.5

# Map IELTS criterion names to our mistake categories so blockers can borrow
# real recurring-mistake evidence for their explanation.
_CRITERION_CATEGORY = {
    "Task Achievement": "task_response",
    "Task Response": "task_response",
    "Coherence & Cohesion": "coherence",
    "Lexical Resource": "vocabulary",
    "Grammatical Range & Accuracy": "grammar",
    "Grammar Range & Accuracy": "grammar",
    "Fluency & Coherence": "fluency",
    "Pronunciation": "pronunciation",
}


def compute_band_gap(db: Session, user_id: int, target: float = DEFAULT_TARGET) -> dict:
    bands = skill_bands(db, user_id)
    if not bands:
        return {
            "current": None,
            "target": round(target, 1),
            "gap": None,
            "per_skill": {},
            "lowest_skill": None,
            "has_data": False,
        }

    overall = _round_half(mean(bands.values()))
    gap = round(max(0.0, target - overall), 1)
    lowest_skill = min(bands, key=lambda s: bands[s])

    return {
        "current": overall,
        "target": round(target, 1),
        "gap": gap,
        "per_skill": {s: round(b, 1) for s, b in bands.items()},
        "lowest_skill": lowest_skill,
        "has_data": True,
    }


def _explanation_from_mistakes(db: Session, user_id: int, skill: str, category: str | None) -> str | None:
    """Borrow the most recurring subskill in this skill+category as evidence."""
    if not category:
        return None
    recent_ids = recent_submission_ids(db, user_id, skill, limit=8)
    if not recent_ids:
        return None
    rows = (
        db.query(Mistake)
        .filter(
            Mistake.user_id == user_id,
            Mistake.skill == skill,
            Mistake.category == category,
            Mistake.submission_id.in_(recent_ids),
        )
        .all()
    )
    if not rows:
        return None
    per_subskill: dict[str, set] = defaultdict(set)
    for m in rows:
        per_subskill[m.subskill or category].add(m.submission_id)
    subskill, subs = max(per_subskill.items(), key=lambda kv: len(kv[1]))
    label = subskill.replace("_", " ")
    return f"Frequent {label} issues — seen in {len(subs)} of your last {len(recent_ids)} attempts."


def generate_blockers(db: Session, user_id: int, target: float = DEFAULT_TARGET, limit: int = 3) -> list[dict]:
    """Top blockers = the lowest-scoring criteria across Writing & Speaking."""
    candidates: list[dict] = []

    for skill in ("writing", "speaking"):
        feedback = latest_feedback(db, user_id, skill)
        if not feedback:
            continue
        criteria = feedback.get("criteria") or {}
        for criterion, band in criteria.items():
            if band is None or band <= 0:
                continue
            category = _CRITERION_CATEGORY.get(criterion)
            explanation = _explanation_from_mistakes(db, user_id, skill, category) or (
                f"{criterion} is currently your weakest area in {skill.title()}."
            )
            candidates.append(
                {
                    "skill": skill.title(),
                    "criterion": criterion,
                    "band_cap": round(float(band), 1),
                    "explanation": explanation,
                    "fix_href": practice_href(skill),
                }
            )

    # Lowest band = biggest blocker. Only surface criteria below target.
    below_target = [c for c in candidates if c["band_cap"] < target]
    pool = below_target or candidates
    pool.sort(key=lambda c: c["band_cap"])
    return pool[:limit]
